//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelDashApp.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPWreset
    {
        public System.Guid UserPin { get; set; }
        public int UserId { get; set; }
        public System.DateTime requestDT { get; set; }
        public Nullable<System.DateTime> resetDT { get; set; }
        public Nullable<bool> reset { get; set; }
    }
}
